from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from app.services.architecture_map import build_architecture_map
from app.services.onboarding_assistant import build_onboarding_guide
from app.services.repo_scanner import scan_repository

REPORTS_DIR = Path("./reports")


def _safe_name(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-")


def _list_section(title: str, items: list[str]) -> str:
    if not items:
        return f"## {title}\n\n- None detected\n"
    lines = "\n".join(f"- {item}" for item in items)
    return f"## {title}\n\n{lines}\n"


def _kv_section(title: str, mapping: dict[str, Any]) -> str:
    if not mapping:
        return f"## {title}\n\n- No data available\n"
    lines = "\n".join(f"- **{key}**: {value}" for key, value in mapping.items())
    return f"## {title}\n\n{lines}\n"


def _module_section(modules: list[dict[str, Any]]) -> str:
    if not modules:
        return "## Top Modules\n\n- No modules detected\n"
    lines = "\n".join(f"- **{item['module']}**: {item['files']} files" for item in modules)
    return f"## Top Modules\n\n{lines}\n"


def build_markdown_report(repo_path: str, repo_label: str | None = None) -> dict[str, Any]:
    scan_result = scan_repository(repo_path)
    architecture_map = build_architecture_map(repo_path)
    onboarding_guide = build_onboarding_guide(repo_path)

    repo_name = repo_label or scan_result["repo_name"]
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    metadata = {
        "Repo Name": repo_name,
        "Repo Path": scan_result["repo_path"],
        "Generated At": timestamp,
        "Total Files": scan_result["total_files"],
        "Frameworks": ", ".join(scan_result.get("frameworks", [])) or "None",
        "Languages": ", ".join(f"{k} ({v})" for k, v in scan_result.get("languages", {}).items()) or "None",
    }

    summary_lines = [
        f"# {repo_name} — Engineering Report",
        "",
        "This report was generated by CodeGraph AI.",
        "",
    ]

    markdown = "\n".join(summary_lines)
    markdown += _kv_section("Repository Metadata", metadata)
    markdown += _module_section(architecture_map.get("top_modules", []))
    markdown += _list_section("Entry Points", architecture_map.get("entry_points", []))
    markdown += _list_section("API Routes", architecture_map.get("api_routes", []))
    markdown += _list_section("Services", architecture_map.get("services", []))
    markdown += _list_section("Data Models", architecture_map.get("data_models", []))
    markdown += _list_section("Data Access", architecture_map.get("data_access", []))
    markdown += _list_section("Frontend", architecture_map.get("frontend", []))
    markdown += _list_section("Config / Infra", architecture_map.get("config_infra", []))
    markdown += _list_section("Tests", architecture_map.get("tests", []))
    markdown += _list_section("Docs", architecture_map.get("docs", []))
    markdown += _list_section("Likely Request Flow", onboarding_guide.get("likely_workflows", []))
    markdown += _list_section("First Files To Read", onboarding_guide.get("first_files_to_read", []))
    markdown += _list_section("Recommended Learning Path", onboarding_guide.get("learning_path", []))
    markdown += _list_section("Focus Areas", onboarding_guide.get("focus_areas", []))

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"{_safe_name(repo_name)}_engineering_report_{stamp}.md"
    output_path = REPORTS_DIR / filename
    output_path.write_text(markdown, encoding="utf-8")

    return {
        "repo_name": repo_name,
        "repo_path": scan_result["repo_path"],
        "report_path": str(output_path.resolve()),
        "markdown_preview": markdown[:12000],
        "architecture_map": architecture_map,
        "onboarding_guide": onboarding_guide,
    }
