from __future__ import annotations

from datetime import datetime
from html import escape
from pathlib import Path
from typing import Any

from app.services.architecture_map import build_architecture_map
from app.services.dependency_insights import build_dependency_insights
from app.services.deployment_readiness import build_deployment_readiness
from app.services.onboarding_assistant import build_onboarding_guide
from app.services.repo_scanner import scan_repository
from app.services.system_design_explainer import build_system_design_explanation
from app.services.test_coverage_heuristics import build_test_coverage_heuristics

SHARES_DIR = Path("./shares")


def _safe_name(value: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "-" for ch in value).strip("-")


def _ul(items: list[str]) -> str:
    if not items:
        return "<ul><li>None</li></ul>"
    return "<ul>" + "".join(f"<li>{escape(str(item))}</li>" for item in items) + "</ul>"


def _kv_table(mapping: dict[str, Any]) -> str:
    if not mapping:
        return "<p>None</p>"
    rows = []
    for key, value in mapping.items():
        rows.append(
            f"<tr><td><strong>{escape(str(key))}</strong></td><td>{escape(str(value))}</td></tr>"
        )
    return "<table>" + "".join(rows) + "</table>"


def _module_list(modules: list[dict[str, Any]]) -> str:
    if not modules:
        return "<ul><li>None</li></ul>"
    return "<ul>" + "".join(
        f"<li><strong>{escape(item['module'])}</strong> — {item['files']} files</li>"
        for item in modules
    ) + "</ul>"


def build_share_snapshot(repo_path: str, repo_label: str | None = None) -> dict[str, Any]:
    scan_result = scan_repository(repo_path)
    architecture = build_architecture_map(repo_path)
    onboarding = build_onboarding_guide(repo_path)
    dependency = build_dependency_insights(repo_path)
    system_design = build_system_design_explanation(repo_path)
    test_coverage = build_test_coverage_heuristics(repo_path)
    deployment = build_deployment_readiness(repo_path)

    repo_name = repo_label or scan_result["repo_name"]
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")

    summary_kv = {
        "Repo Name": repo_name,
        "Repo Path": scan_result["repo_path"],
        "Generated At": generated_at,
        "Total Files": scan_result["total_files"],
        "Frameworks": ", ".join(scan_result.get("frameworks", [])) or "None",
        "Languages": ", ".join(f"{k} ({v})" for k, v in scan_result.get("languages", {}).items()) or "None",
        "Deployment Score": f"{deployment['score']} ({deployment['level']})",
        "Coverage Heuristic": f"{test_coverage['counts']['coverage_heuristic_percent']}%",
    }

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>{escape(repo_name)} — Share Snapshot</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      margin: 0;
      background: #0b1020;
      color: #e8ecf3;
      line-height: 1.5;
    }}
    .wrap {{
      max-width: 1100px;
      margin: 0 auto;
      padding: 32px 20px 60px;
    }}
    h1, h2, h3 {{
      margin: 0 0 12px;
    }}
    h1 {{
      font-size: 32px;
    }}
    h2 {{
      margin-top: 28px;
      font-size: 22px;
      border-bottom: 1px solid #2b3553;
      padding-bottom: 8px;
    }}
    .hero {{
      background: linear-gradient(135deg, #18233f, #10182f);
      border: 1px solid #2b3553;
      border-radius: 18px;
      padding: 24px;
      margin-bottom: 24px;
    }}
    .muted {{
      color: #9fb0d1;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
      gap: 16px;
      margin-top: 16px;
    }}
    .card {{
      background: #121a31;
      border: 1px solid #2b3553;
      border-radius: 16px;
      padding: 16px;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }}
    td {{
      border-bottom: 1px solid #24304d;
      padding: 8px 6px;
      vertical-align: top;
    }}
    ul {{
      margin: 10px 0 0;
      padding-left: 20px;
    }}
    code {{
      background: #1a2443;
      padding: 2px 6px;
      border-radius: 6px;
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <section class="hero">
      <h1>{escape(repo_name)} — Portfolio Snapshot</h1>
      <p class="muted">Generated by CodeGraph AI on {escape(generated_at)}</p>
      {_kv_table(summary_kv)}
    </section>

    <h2>System Design Narrative</h2>
    <div class="card"><p>{escape(system_design['narrative'])}</p></div>

    <h2>Top Modules</h2>
    <div class="card">{_module_list(architecture.get("top_modules", []))}</div>

    <h2>Architecture Signals</h2>
    <div class="grid">
      <div class="card"><h3>Entry Points</h3>{_ul(architecture.get("entry_points", []))}</div>
      <div class="card"><h3>API Routes</h3>{_ul(architecture.get("api_routes", []))}</div>
      <div class="card"><h3>Services</h3>{_ul(architecture.get("services", []))}</div>
      <div class="card"><h3>Data Access</h3>{_ul(architecture.get("data_access", []))}</div>
      <div class="card"><h3>Frontend</h3>{_ul(architecture.get("frontend", []))}</div>
      <div class="card"><h3>Config / Infra</h3>{_ul(architecture.get("config_infra", []))}</div>
    </div>

    <h2>Onboarding Guide</h2>
    <div class="grid">
      <div class="card"><h3>First Files To Read</h3>{_ul(onboarding.get("first_files_to_read", []))}</div>
      <div class="card"><h3>Learning Path</h3>{_ul(onboarding.get("learning_path", []))}</div>
      <div class="card"><h3>Likely Workflows</h3>{_ul(onboarding.get("likely_workflows", []))}</div>
      <div class="card"><h3>Focus Areas</h3>{_ul(onboarding.get("focus_areas", []))}</div>
    </div>

    <h2>Dependencies & Tooling</h2>
    <div class="grid">
      <div class="card"><h3>Package Managers</h3>{_ul(dependency.get("package_managers", []))}</div>
      <div class="card"><h3>Infra / Build Files</h3>{_ul(dependency.get("infra_files", []))}</div>
    </div>
    <div class="card"><h3>Dependency Files</h3><pre>{escape(str(dependency.get("dependency_files", {})))}</pre></div>

    <h2>Testing Posture</h2>
    <div class="grid">
      <div class="card"><h3>Coverage Stats</h3>{_kv_table(test_coverage.get("counts", {}))}</div>
      <div class="card"><h3>Detected Test Frameworks</h3>{_ul(test_coverage.get("detected_test_frameworks", []))}</div>
      <div class="card"><h3>Risky Untested Files</h3>{_ul(test_coverage.get("risky_untested_files", []))}</div>
    </div>

    <h2>Deployment Readiness</h2>
    <div class="grid">
      <div class="card"><h3>Readiness</h3>{_kv_table({"Score": deployment["score"], "Level": deployment["level"]})}</div>
      <div class="card"><h3>Reasons</h3>{_ul(deployment.get("reasons", []))}</div>
      <div class="card"><h3>Recommended Actions</h3>{_ul(deployment.get("recommended_actions", []))}</div>
    </div>

    <h2>Design Risks / Gaps</h2>
    <div class="card">{_ul(system_design.get("design_risks", []))}</div>
  </div>
</body>
</html>
"""

    SHARES_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"{_safe_name(repo_name)}_share_snapshot_{stamp}.html"
    output_path = SHARES_DIR / filename
    output_path.write_text(html, encoding="utf-8")

    return {
        "repo_name": repo_name,
        "repo_path": scan_result["repo_path"],
        "share_path": str(output_path.resolve()),
        "generated_at": generated_at,
        "highlights": {
            "frameworks": scan_result.get("frameworks", []),
            "top_modules": architecture.get("top_modules", [])[:5],
            "deployment_score": deployment["score"],
            "coverage_heuristic_percent": test_coverage["counts"]["coverage_heuristic_percent"],
        },
    }
